#!/usr/bin/env python3
"""Generate the MSP reference markdown from the schema.

Reads schema/msp_v2.yaml and schema/enums.yaml and writes the MSP reference into
docs/development/msp/ (README.md = messages, enums.md = enums). The schema is the
source of truth; this is a rendered
view of it, regenerated by build.sh — not hand-edited.

Usage:
    python3 gen_docs.py [--schema DIR] [--out DIR]
"""
from __future__ import annotations

import argparse
import sys
import yaml
from pathlib import Path

HERE = Path(__file__).resolve().parent
MSP_ROOT = HERE.parent
REPO_ROOT = MSP_ROOT.parent


def field_rows(fields: dict, out: list, indent: str = "") -> None:
    for name, spec in (fields or {}).items():
        if isinstance(spec, dict) and "repeat" in spec:
            out.append(f"| {indent}{name}[] | *repeat: {spec['repeat']}* | | |")
            field_rows(spec.get("fields") or {}, out, indent + " ")
            continue
        if isinstance(spec, str):
            out.append(f"| {indent}{name} | `{spec}` | | |")
            continue
        typ = spec.get("type", "")
        ann = spec.get("enum") or (("bitmask " + spec["bitmask"]) if isinstance(spec.get("bitmask"), str) else "")
        if spec.get("bitmask") is True and spec.get("enum"):
            ann = f"{spec['enum']} (bitmask)"
        elif spec.get("bitmask") is True:
            ann = "bitmask"
        desc = (spec.get("description") or "").replace("\n", " ").replace("|", "\\|")
        unit = spec.get("unit", "")
        out.append(f"| {indent}{name} | `{typ}` | {('`'+ann+'`') if ann else ''} {unit} | {desc} |")


def payload_md(title: str, spec, out: list) -> None:
    if not isinstance(spec, dict) or not (spec.get("fields") or spec.get("repeat")):
        out.append(f"*{title}:* none\n")
        return
    out.append(f"*{title}:*" + (f" (repeat: {spec['repeat']})" if spec.get("repeat") else ""))
    out.append("")
    out.append("| Field | Type | Enum / flags | Description |")
    out.append("|---|---|---|---|")
    rows: list = []
    field_rows(spec.get("fields") or {}, rows)
    out.extend(rows)
    out.append("")


def gen_messages(doc: dict) -> str:
    msgs = doc["messages"]
    out = ["# INAV MSP messages",
           "",
           "**Generated from `msp/schema/msp_v2.yaml` by `./msp/build.sh generate` — do not edit by hand.**",
           "",
           "`msp/schema/msp_v2.yaml` is the single hand-authored source of truth for the MSP "
           "protocol. Enums and constants are harvested from the INAV C source. To change the "
           "protocol, edit the schema and run `./msp/build.sh generate`; CI fails the build if this "
           "file is out of date.",
           "",
           "Enum reference: [`enums.md`](enums.md). See also [`format.md`](format.md) and "
           "[`msp-message-routing-architecture.md`](msp-message-routing-architecture.md).",
           "", f"{len(msgs)} messages.", "", "## Contents", ""]
    for name in msgs:
        out.append(f"- [{name}](#{name.lower()})")
    out.append("")
    for name, m in msgs.items():
        out.append("---")
        code = m["id"]
        idtxt = f"`0x{code:04X}` ({code})" if m.get("mspv") == 2 else f"`{code}`"
        out.append(f"## {name}")
        out.append("")
        out.append(f"id {idtxt} · MSPv{m.get('mspv')} · group `{m.get('group')}`"
                   + ("  ·  *not implemented*" if m.get("not_implemented") else ""))
        out.append("")
        iv = m.get("inav_version")
        if iv:
            line = f"since INAV {iv['since']}"
            if iv.get("until"):
                line += f" · deprecated, kept for compatibility until {iv['until']}"
            out.append(line)
            out.append("")
        if m.get("description"):
            out.append(m["description"] + "\n")
        if m.get("notes"):
            out.append(f"> {m['notes']}\n")
        if m.get("variants"):
            for vkey, shape in m["variants"].items():
                out.append(f"**variant: {vkey}**\n")
                payload_md("request", shape.get("request"), out)
                payload_md("reply", shape.get("reply"), out)
        else:
            payload_md("request", m.get("request"), out)
            payload_md("reply", m.get("reply"), out)
    return "\n".join(out) + "\n"


def gen_enums(enums_doc: dict) -> str:
    enums = enums_doc.get("enums") or {}
    out = ["# INAV enums (MSP reference)",
           "",
           "Harvested from INAV C source into `msp/schema/enums.yaml` by "
           "`msp/generator/harvest_enums.py`; rendered by `gen_docs.py`. Do not edit by hand.",
           "", f"{len(enums)} enums.", ""]
    for name in sorted(enums):
        body = enums[name]
        out.append("---")
        out.append(f"## `{name}`")
        if body.get("description"):
            out.append(f"> {body['description']}")
        out.append("")
        out.append("| Member | Value | Condition |")
        out.append("|---|---:|---|")
        for v in body.get("values") or []:
            if isinstance(v, dict):
                out.append(f"| `{v['name']}` | {v['value']} | {v.get('condition','')} |")
            else:
                head, _, tail = str(v).partition(" = ")
                out.append(f"| `{head.strip()}` | {tail.strip()} | |")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--schema", type=Path, default=MSP_ROOT / "schema")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "docs" / "development" / "msp")
    args = ap.parse_args()

    doc = yaml.safe_load((args.schema / "msp_v2.yaml").read_text())
    enums_doc = yaml.safe_load((args.schema / "enums.yaml").read_text())
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "README.md").write_text(gen_messages(doc))
    (args.out / "enums.md").write_text(gen_enums(enums_doc))
    print(f"wrote {args.out}/README.md and {args.out}/enums.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
