"""Generated by gen_pydantic.py from the MSP YAML schema. Do not edit."""

from __future__ import annotations

from enum import IntEnum, IntFlag
from typing import Annotated, Final

from pydantic import BaseModel, ConfigDict, Field


ADSB_CALL_SIGN_MAX_LENGTH: Final[int] = 9
BUILD_DATE_LENGTH: Final[int] = 11
BUILD_TIME_LENGTH: Final[int] = 8
CUSTOM_ELEMENTS_PARTS: Final[int] = 3
DEBUG32_VALUE_COUNT: Final[int] = 8
GIT_SHORT_REVISION_LENGTH: Final[int] = 8
HARDWARE_TIMER_DEFINITION_COUNT: Final[NoneType] = None
LED_CONFIGURABLE_COLOR_COUNT: Final[int] = 16
LED_MAX_STRIP_LENGTH: Final[int] = 128
MAX_ADJUSTMENT_RANGE_COUNT: Final[int] = 20
MAX_GLOBAL_VARIABLES: Final[int] = 8
MAX_LOGIC_CONDITIONS: Final[int] = 64
MAX_MAPPABLE_RX_INPUTS: Final[int] = 4
MAX_MODE_ACTIVATION_CONDITION_COUNT: Final[int] = 40
MAX_PROGRAMMING_PID_COUNT: Final[int] = 4
MAX_SERVO_RULES: Final[int] = 36
MAX_SUPPORTED_MOTORS: Final[NoneType] = None
MAX_SUPPORTED_SERVOS: Final[int] = 18
MAX_TEMP_SENSORS: Final[int] = 8
OSD_CHAR_BYTES: Final[int] = 64
OSD_CHAR_VISIBLE_BYTES: Final[int] = 54
OSD_ITEM_COUNT: Final[int] = 172
PID_ITEM_COUNT: Final[int] = 12
RADAR_MAX_POIS: Final[int] = 5
TEMPERATURE_LABEL_LEN: Final[int] = 4
